platform :ios, '10.0'

install! 'cocoapods', :disable_input_output_paths => true
inhibit_all_warnings!
use_frameworks!

target 'TezosSwift_Example' do
	pod 'TezosSwift', :path => '../'

	target "UnitTests" do
    	inherit! :complete
	end

	target "IntegrationTests" do
    	inherit! :complete
	end
end
