use_modular_headers!
use_frameworks!
target 'TezosSwift_Example' do
	pod 'TezosSwift', :path => '../'

	target "UnitTests" do
    	inherit! :search_paths
	end

	target "IntegrationTests" do
    	inherit! :search_paths
	end
end
