platform :ios, '10.0'

inhibit_all_warnings!
use_frameworks!

target 'TezosSwift_Example' do
	pod 'TezosSwift', :path => '../'

	target "UnitTests" do
    	inherit! :complete
	end

	target "IntegrationTests" do
    	inherit! :complete
	end
end
