os: osx
language: objective-c
xcode_project: TezosKit.xcodeproj
xcode_scheme: TezosKit
xcode_sdk: iphonesimulator12.0

script:
- set -o pipefail && xcodebuild -workspace TezosKit.xcworkspace -scheme TezosKitExampleApp -destination platform\=iOS\ Simulator,OS\=12.0,name\=iPhone\ X -UseModernBuildSystem=YES build | xcpretty && exit ${PIPESTATUS[0]}
  
before_install:
  - brew update
  - brew install libsodium