language: swift
os: osx
osx_image: xcode10

script:
  - set -o pipefail && xcodebuild -enableCodeCoverage=YES -workspace TezosKit.xcworkspace -scheme TezosKitTests -destination platform\=iOS\ Simulator,OS\=12.0,name\=iPhone\ X -UseModernBuildSystem=YES build test | xcpretty && exit ${PIPESTATUS[0]}
after_success:
  - echo "Uploading..." && bash <(curl -s https://codecov.io/bash) && echo "Upload finished."
  
before_install:
  - brew update
  - brew install libsodium
