osx_image: xcode11
language: objective-c
env:
  global:
  - FRAMEWORK_NAME=TezosSwift
before_install:
# - brew update
# - brew outdated carthage || brew upgrade carthage
- carthage bootstrap --platform iOS 
before_deploy:
- carthage build --no-skip-current --platform iOS 
- carthage archive $FRAMEWORK_NAME
after_deploy:
- pod trunk push --skip-import-validation --skip-tests --allow-warnings
script:
- set -o pipefail && xcodebuild test -scheme TezosSwift -destination 'platform=iOS
  Simulator,name=iPhone 11,OS=13.0' ONLY_ACTIVE_ARCH=YES | xcpretty
deploy:
  provider: releases
  api_key:
    secure: kHuRamm7EGWs+C2e6890GJRJ9D1SCgMwU0d87eyDf/vJjCAPfg8OHKcitdhViYFenKklgFaiwEsTx3V/tHEq/v/uXKywmxoXs7a2K7P9rFRLuWikd4p3g7ZjA5lJMt5mKdx7LFDfuL6qWcPvg81a0utcQm6qOERaJxiyGwWqpRtKLzbags53v8yQ3JZpl88ilGeRjbFBcIyJFTjr2AZ4Ko7Yx/xGvXjxuEbTWxeSKvEG31X7zSO962Kva/OjI1R9sJSdw3Lh0MQreP0JnhePck+8Z1t6w/0D1lSBUMz0+g8MwG6o9P1xTcXG3lhrUqsjhmIpBeNEogSgxkvyYqR8d7ocgUwj8JRNLOKFj31ThoWA0BBsB1OjBDqqVdzJYPZrrr8TZL9o0a9XCneVzchCjBpAQQrC2ay28cGOaKRZlnnfgyGaPoGAWspijpK99+Di8vOcoXTalz7wnxYJIR/KdzAGOy0W/dyBFKRIwG+oaIl9j1K+Yh75uNy9C09dnPue+TUwplohyDCE9ZguaTQJ3aGEvgOzTRRr4n0ziCN1QMLRf/+Zb6XnN/tHSimGf98IWvPPJvEzJbpTV8C9HAzE+lMCC6S21dzNuagZf7UCv3VmH7gWpbtToZcaj3CAisqPVgP+Nh39R9rvJz2IfQeVIm61z2mhy9mbq4frEka4yNk=
  file: "$FRAMEWORK_NAME.framework.zip"
  skip_cleanup: true
  on:
    repo: AckeeCZ/TezosSwift
    tags: true
