os: osx
language: objective-c
xcode_project: TezosKit.xcodeproj
xcode_scheme: TezosKit

script:
- set -o pipefail && xcodebuild -workspace Optimize.xcworkspace -scheme ProdApp -destination platform\=iOS\ Simulator,OS\=12.0,name\=iPhone\ X -UseModernBuildSystem=NO build test | xcpretty && exit ${PIPESTATUS[0]}

before_install:
  - brew update
  - brew install libsodium