language: swift
os: osx
osx_image: xcode10

script:
- set -o pipefail && xcodebuild -workspace TezosKit.xcworkspace -scheme TezosKitExampleApp -destination platform\=iOS\ Simulator,OS\=12.0,name\=iPhone\ X -UseModernBuildSystem=YES build | xcpretty && exit ${PIPESTATUS[0]}
  
before_install:
  - brew update
  - brew install libsodium